config/routes.rb
Rails.application.routes.draw do

  get '/error', to: 'errors#not_found'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :posts


  root 'sessions#new'
  get '*path', to: 'errors#not_found'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_secure_password
  validates :email, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  # def internal_server_error
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login

  def new
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.find(session[:user_id])
    post = @user.posts.create(posts_params)
    @post = Post.find(post.id)

    if @post.wall_id == nil
      redirect_to posts_url
    else
      redirect_to user_url(@post.wall_id)
    end
  end

  def edit
    @user = User.find(session[:user_id])
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(edit_params)

    if @post.wall_id == nil
      redirect_to posts_url
    else
      redirect_to user_url(@post.wall_id)
    end
  end

  def index
    @posts = Post.where(:wall_id => nil)
    @user = User.find(session[:user_id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_url
  end

  private

  def edit_params
    params.require(:post).permit(:message)
  end

  def posts_params
    {
      message: params.require(:post).permit(:message)[:message],
      wall_id: params[:user][:id]
    }
  end

  def require_login
    redirect_to root_path unless logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to user_url(@user)
    else
      flash.now[:danger] = 'Invalid credentials'
      render 'new'
    end
  end




  def destroy
    session.clear
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, except: [:new, :create]

  def show
    @user = User.find(params[:id])
    @posts = Post.where(:wall_id =>@user.id)
    @current_user = User.find(session[:user_id])
  end

  def new
  end

  def create
    @userdbcheck = User.find_by(email: user_params[:email])
    if @userdbcheck == nil
      @user = User.new(user_params)
      @user.save
      redirect_to login_path
    else
      flash.now[:danger] = 'Email has already been taken'
      render 'new'
    end
  end

  def index
    @users = User.all
    @user = User.find(session[:user_id])
  end

  private

  def require_login
    redirect_to root_path unless logged_in?
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">

  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet">
  <title>Bearbook - Edit Posts</title>
</head>

<body>

<%= render "shared/menu" %>

  <div class="posts_wrapper">
    <div class="post_new_container">

      <%= form_with(model: @post, local: true) do |form| %>

      <div class="bear_icon_post_new">&nbsp; &#128059; &nbsp;
        <span id="special-text">Edit Message</span></div>

      <div class="new_post_label">
        <%= form.label :message %><br>
      </div>

      <div class="new_post_message">
        <%= form.text_area :message %>
      </div>

      <div class="new_post_button">
        <%= form.submit "Update message", class: :btn %>
      </div>

      <% end %>
    </div>
  </div>

</body>

</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet">
    <title>Bearbook - Posts</title>
  </head>
  <body>

  <%= render "shared/menu" %>

  <div class="posts_wrapper">

    <div class="new_post_link_button">
      <div class="new_post_link">
        <%= link_to new_post_path do %>
        New post
      <% end %>
    </div>
  </div>

  <% @posts.reverse.each do |post| %>
    <div class="post_container">

      <div class="bear_icon_post">&#128059;</div>

      <div class="user_name_post"><%=post.user.first_name.capitalize%>
        <%=post.user.last_name.capitalize%></div>

      <div class="user_content_post"><%= simple_format(post.message) %></div>

      <div class="time_of_post"><%= post.created_at %></div>

      <div class="delete_post">
        <% if post.user.id == @user.id %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <span>-</span>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
      </div>

    </div>

  <% end %>

</div>

</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet">
    <title>Bearbook - Posts</title>
  </head>
  <body>
  <%= render "shared/menu" %>

    <div class="posts_wrapper">

      <div class="post_new_container">
        <%= form_with scope: :post, url: posts_path, local: true do |form| %>

        <div class="bear_icon_post_new">&nbsp; &#128059; &nbsp;
          <span id="special-text">Message</span></div>

        <div class="new_post_label">
          <%= form.label :message %>
        </div>

        <div class="new_post_message">
          <%= form.text_area :message, placeholder: "What are the bear necessities..." %>
        </div>
        <% @user.id = nil %>
        <%=hidden_field(:user, :id)%>

        <div class="new_post_button">
          <%= form.submit "Submit", class: :btn %>
        </div>

        <% end %>
      </div>
    </div>

  </body>
</html>

app/views/shared/_menu.html.erb
<div class="page_wrapper">

  <div class="menu_container">

    <div class="menu">

      <div class="left-hand-side">
        <div class="welcome">
          Welcome
          <%= @user.first_name.capitalize %>
        </div>
      </div>

      <div class="right-hand-side">

        <div class="logout">
          <%= link_to @user do %>
          &#128059; Profile
          <% end %>
          <%= link_to posts_path do %>
          Posts
          <% end %>
          <%= link_to users_path do %>
          Users
          <% end %>
          <%= link_to logout_path, method: :delete do %>
          Logout
          <% end %>
        </div>

      </div>

    </div>

  </div>

</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet">
    <title>Bearbook - Posts</title>
  </head>
  <body>

  <%= render "shared/menu" %>

    <div class="user-wrapper">
      <div class="user-list">
        <h2>User Directory</h2>
        <% @users.each do |user| %>
          <%= user.first_name.capitalize %>
          <%= user.last_name.capitalize %>
          <%= link_to user.email, user_path(user) %>
          <br>
        <% end %>
      </div>
    </div>

  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet">
    <title>Bearbook - Signup</title>
  </head>

  <body>

    <div class="wrapper">
      <div class="sign-up">
        <h1>Bearbook</h1>
        <p id="bear-icon">&#128059;</p>

        <% if flash[:danger] %>
          <div class="login-notice"><%= flash[:danger] %></div>
        <% end %>

        <%= form_with scope: :user, url: users_path, local: true do |form| %>

        <%= form.label :first_name %><br>
        <%= form.text_field :first_name %>

        <br>

        <%= form.label :last_name %><br>
        <%= form.text_field :last_name %>

        <br>

        <%= form.label :email %><br>
        <%= form.text_field :email %>

        <br>

        <%= form.label :password %><br>
        <%= form.password_field :password %>

        <br>

        <%= form.submit "Signup", :class => 'btn' %>

      <% end %>
    </div>
  </div>

</body>

</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet">
    <title>Bearbook - Posts</title>
  </head>
  <body>

    <div class="page_wrapper">

      <div class="menu_container">

        <div class="menu">

          <div class="left-hand-side">
            <div class="welcome">
              Welcome
              <%= @current_user.first_name.capitalize %>
            </div>
          </div>

          <div class="right-hand-side">

            <div class="logout">
              <%= link_to @current_user do %>
              &#128059; Profile
              <% end %>
              <%= link_to posts_path do %>
              Posts
              <% end %>
              <%= link_to users_path do %>
              Users
              <% end %>
              <%= link_to logout_path, method: :delete do %>
              Logout
              <% end %>
            </div>

          </div>

        </div>

      </div>

    </div>

    <div class="user-wall-wrapper">

      <div class="user-wall-details">
        <div class="profile-pic">
          &#128059;
        </div>
        <div class="user-details-box">
          <div class="user-wall-name">
            <p>Name: <%= @user.first_name %> <%= @user.last_name %></p>
          </div>
          <div class="user-wall-email">
            <p>Email: <%= @user.email %></p>
          </div>
        </div>
      </div>

      <div class="post_new_container">
        <%= form_with scope: :post, url: posts_path, local: true do |form| %>

        <div class="bear_icon_post_new">&#128059; &nbsp;
          <span id="special-text">Message</span></div>

        <div class="new_post_label">
          <%= form.label :message %>
        </div>

        <div class="new_post_message">
          <%= form.text_area :message, placeholder: "What are the bear necessities..." %>
        </div>

        <%= hidden_field(:user, :id) %>

        <div class="new_post_button">
          <%= form.submit "Submit", class: :btn %>
        </div>

        <% end %>
      </div>

      <% @posts.reverse.each do |post| %>
        <div class="post_container">

          <div class="bear_icon_post">&#128059;</div>

          <div class="user_name_post"><%=post.user.first_name.capitalize%>
            <%=post.user.last_name.capitalize%></div>

          <div class="user_content_post"><%= simple_format(post.message) %></div>

          <div class="time_of_post"><%= post.created_at %></div>

          <div class="delete_post">
            <% if post.user.id == @current_user.id %>
              <%= link_to 'Edit', edit_post_path(post) %>
              <span>-</span>
              <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
            <%end%>
          </div>

        </div>

      <% end %>

    </div>

  </body>

</html>